### ISSUE TITLE
Could you offer the .CRX fie?

### ISSUE THREAD

**Issue by xngnln** [PageMonitorPlus/pagemon-chrome-ext#3]
I got a new laptop, my new chrome didn't auto sync the Page Monitor Plus extension, then I found that the Page Monitor Plus was taken down.
I tried to use the code to pack this extension, but the new one didn't work, the ID is not the same as the old Page Monitor Plus in the store, could you please offer the .CRX of the same ID?
My email is xngnln@gmail.com. Thanks a lot!

**Comment by chromaniac2** [comment]
I thought this solved all the issues? 
https://chrome.google.com/webstore/detail/page-monitor/ogeebjpdeabhncjpfhgdibjajcajepgg

**Comment by xngnln** [comment]
I think the original Page Monitor is better, the new one is Visualping, the original has been sellout to Visualping, they are different, I have downloaded the original Page Monitor CRX file, but it updated to the newer Visualping, so the Page Monitor Plus is my only hope.

**Comment by chromaniac2** [comment]
please check the link above. the developer released the original page monitor separately for people who were not happy with visual ping update.

**Comment by xngnln** [comment]
Oh! I'm so silly, I spent a whole day to solve this problem, but didn't install that, thank you very much!
